### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by multimeric** [jackdesert/freecinc#11]
Hi, I'm interesting in hosting my own taskd server, but using freecinc to give me the certificate generation and web UI for doing so. Is there a docker image for doing this? If not, is there any interest in me contributing one?

**Comment by djmitche** [comment]
In a way, yes -- head on over to https://github/freecinc and you'll see some repos to build the web and taskd portions of the service, plus some helm to glue it all together.  It's not quite done yet -- progress is tracked [here](https://github.com/orgs/freecinc/projects/1) -- but will soon be used for hosting freecinc.com itself.  Any contribution would be welcome!  In particular, it might be helpful to add some customization of the UI based on a name, so that your UI could look a bit different from the freecinc.com UI.
